picsumReplicas: 3
picsumCreateImageManifest: true

imageServiceReplicas: 4

cloudflareAuthEnabled: true
externalDNSEnabled: true

picsumPhotosDockerImage: 'registry.digitalocean.com/picsum-registry/picsum-photos@sha256:f35a40671b932e04a3eb6692a3cf7eb08c18ec060aae3aa509843b90577c9675'
imageServiceDockerImage: 'registry.digitalocean.com/picsum-registry/picsum-photos@sha256:f35a40671b932e04a3eb6692a3cf7eb08c18ec060aae3aa509843b90577c9675'
