---
- name: Upgrade existing packages
  apt: upgrade=full update_cache=yes

- name: Create unsplash user
  user: name=unsplash shell=/bin/bash createhome=yes system=yes

- name: Create ssh directory
  file: path=/home/unsplash/.ssh state=directory owner=unsplash group=unsplash

- name: Copy private key
  copy: src=files/unsplash_rsa dest=/home/unsplash/.ssh/id_rsa owner=unsplash group=unsplash mode=0400

- name: Disable password login for ssh
  lineinfile: dest=/etc/ssh/sshd_config state=absent regexp="^PasswordAuthentication yes"

- name: Disable password login for ssh
  lineinfile: dest=/etc/ssh/sshd_config line="PasswordAuthentication no"
  notify:
    - restart sshd

- name: Add nodejs ppa
  apt_repository: repo='ppa:chris-lea/node.js-devel'

- name: Install required packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - curl
    - nodejs
    - git
    - vnstat
    - htop
    - pkg-config

- name: Update alternatives
  shell: "update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10"

- name: Install global package forever
  shell: "npm install -g forever"

- name: Add github to known_hosts file
  shell: "su unsplash -c 'ssh-keyscan -t rsa github.com > /home/unsplash/.ssh/known_hosts'"

- name: Add dmarby to known_hosts file
  shell: "su unsplash -c 'ssh-keyscan -t rsa dmarby.se > /home/unsplash/.ssh/known_hosts'"

- name: Create photos folder
  file: path=/opt/photos state=directory owner=unsplash group=unsplash

- name: Clone photos repo
  shell: "cd /opt/photos && su unsplash -c 'git clone root@dmarby.se:photos.git /opt/photos'"

- name: Install libvips
  shell: "curl -s https://raw.githubusercontent.com/lovell/sharp/edge/preinstall.sh | bash -"