repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

environments:
  local:
    values:
      - environments/local.yaml
  production:
    values:
      - environments/production.yaml

releases:
  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: "4.3.0"
    values:
      - values/ingress-nginx.yaml

  - name: picsum-photos
    chart: ./charts/picsum-photos
    needs:
     - ingress-nginx/ingress-nginx
    values:
    - values/values.yaml.gotmpl

  # Fixture data for local environment using minio
  - name: fixtures
    chart: ./charts/fixtures
    installed: {{ eq .Environment.Name "local" | toYaml }}
