apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
      - name: image-service
        image: 'dmarby/picsum-photos@sha256:e575eef624cbf5e6ac05fdef9d9f000d042bc9461b95778544b4034224f3e35b'
        command: ['./image-service']
        ports:
        - containerPort: 8081
        resources:
          requests:
            memory: 512Mi
            cpu: 2
          limits:
            memory: 1Gi
            cpu: 3.75
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
        env:
          - name: IMAGE_CACHE
            value: "redis"
          - name: IMAGE_CACHE_REDIS_ADDRESS
            value: "redis://redis-svc.default.svc:6379"
          - name: IMAGE_STORAGE
            value: "spaces"
          - name: IMAGE_STORAGE_SPACES_REGION
            valueFrom:
              secretKeyRef:
                name: picsum-spaces
                key: region
          - name: IMAGE_STORAGE_SPACES_SPACE
            valueFrom:
              secretKeyRef:
                name: picsum-spaces
                key: space
          - name: IMAGE_STORAGE_SPACES_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: picsum-spaces
                key: access_key
          - name: IMAGE_STORAGE_SPACES_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: picsum-spaces
                key: secret_key
          - name: IMAGE_HMAC_KEY
            valueFrom:
              secretKeyRef:
                name: picsum-hmac
                key: hmac_key
      affinity: # Only one pod per node
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - image-service
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: image-service
spec:
  clusterIP: None
  selector:
    app: image-service
  ports:
  - port: 8081
    name: image-service
