apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: picsum-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
      - picsum.photos
      - i.picsum.photos
      secretName: picsum-cert
  rules:
  - host: picsum.photos
    http:
      paths:
      - backend:
          service:
            name: picsum-svc
            port:
              number: 8080
        pathType: ImplementationSpecific
  - host: i.picsum.photos
    http:
      paths:
      - backend:
          service:
            name: varnish
            port:
              number: 80
        pathType: ImplementationSpecific
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
  use-forwarded-headers: "true"
  hsts: "false"
  allow-snippet-annotations: "true"
