apiVersion: apps/v1
kind: Deployment
metadata:
  name: picsum
spec:
  replicas: 2
  selector:
    matchLabels:
      app: picsum
  template:
    metadata:
      labels:
        app: picsum
    spec:
      containers:
      - name: picsum
        image: 'dmarby/picsum-photos@sha256:93f8278c372c68bf2b57ae802e501c20f035183fa23b4e46f235ee6c0079a9d3'
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
        env:
          - name: PICSUM_CACHE
            value: "redis"
          - name: PICSUM_CACHE_REDIS_ADDRESS
            value: "redis://redis-svc.default.svc:6379"
          - name: PICSUM_DATABASE
            value: postgresql
          - name: PICSUM_DATABASE_POSTGRESQL_ADDRESS
            valueFrom:
              secretKeyRef:
                name: picsum-db
                key: connection_string

---
apiVersion: v1
kind: Service
metadata:
  name: picsum-svc
spec:
  clusterIP: None
  selector:
    app: picsum
  ports:
  - port: 8080
    name: picsum
