apiVersion: apps/v1
kind: Deployment
metadata:
  name: picsum
spec:
  replicas: 3
  selector:
    matchLabels:
      app: picsum
  template:
    metadata:
      labels:
        app: picsum
    spec:
      containers:
      - name: picsum
        image: 'dmarby/picsum-photos@sha256:e575eef624cbf5e6ac05fdef9d9f000d042bc9461b95778544b4034224f3e35b'
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 10
        env:
          - name: PICSUM_CACHE
            value: "redis"
          - name: PICSUM_CACHE_REDIS_ADDRESS
            value: "redis://redis-svc.default.svc:6379"
          - name: PICSUM_DATABASE_FILE_PATH
            value: /etc/picsum-images/picsum-images.json
          - name: PICSUM_HMAC_KEY
            valueFrom:
              secretKeyRef:
                name: picsum-hmac
                key: hmac_key
        volumeMounts:
          - name: picsum-images
            mountPath: "/etc/picsum-images"
            readOnly: true
      volumes:
      - name: picsum-images
        configMap:
          name: picsum-images

---
apiVersion: v1
kind: Service
metadata:
  name: picsum-svc
spec:
  clusterIP: None
  selector:
    app: picsum
  ports:
  - port: 8080
    name: picsum
